version: '3.4'

services:
  web:
    build:
      context: .
    volumes:
      - .:/src/app
      - /src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: barbell-hero
