version: '3.4'

volumes:
  postgresql:
services:
  web:
    build:
      context: .
    volumes:
      - .:/src/app
      - /src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: barbell-hero
  test:
    build:
      context: .
    volumes:
      - .:/src/app
      - /src/app/node_modules
    ports:
      - 9229:9229
    command: "yarn test"
    depends_on:
      - test_db
  test_db:
    image: postgres:10
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: barbell-hero
